# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-23 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180721_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='image',
            field=models.ImageField(null=True, upload_to='books', verbose_name='封面'),
        ),
    ]
