# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-23 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_bookinfo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='image',
            field=models.ImageField(null=True, upload_to='book', verbose_name='封面'),
        ),
    ]
