# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-23 15:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180723_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinfo',
            old_name='image',
            new_name='bimage',
        ),
    ]
